export default [
  {
    id: 0,
    status: 'Queue',
    coLivingName: 'Radish vibrant community',
    residentName: 'Jennifer Lawrence',
    applied: '23/2323/23',
    moveIn: '23/2323/2',
    type: 'Listed',
    created: 'sd/sd/sd',
    apps: 5,
    views: 100,
    followers: 10,
    rank: 1,
    pRank: 2,
    author: 'Winston Churchill',
  },
  {
    id: 2,
    status: 'Queue',
    coLivingName: 'Radish vibrant community',
    residentName: 'Jennifer Lawrence',
    applied: '23/2323/23',
    moveIn: '23/2323/2',
    type: 'Listed',
    created: 'sd/sd/sd',
    apps: 5,
    views: 100,
    followers: 10,
    rank: 1,
    pRank: 2,
    author: 'Erica L',
  },
];
